name: testing runner
on:
  push:
    branches: 
      - feature/import
jobs:
  display:
    runs-on: self-hosted
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      
      - name: snyk test 
        uses: snyk/actions@master
        
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: run tests
        run: |
             snyk test --all-projects
             snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        





