name: testing runner
on:
  push:
    branches: 
      - feature/import
jobs:
  display:
    runs-on: self-hosted
    steps:
      - name: "checkout the code"
        uses: actions/checout@v4

      
      - name: "display the messages"
        run: |
             echo " my name is naveen"
             sleep 60
             echo " i am installing the software"





